@startuml
skinparam conditionStyle inside
title Алгоритм системы "Конёк-Горбунок" (Итоговый)

start
:Иван: решить пройти испытания;

if (Первый котёл: ВодныйБафф(50) >= 40?) then (да)
    #lightgreen:Иван выжил в воде;
    :Здоровье = 100;
else (нет)
    #pink:Иван погиб в воде;
    stop
endif

if (Второй котёл: МолочныйБафф(50) >= 60?) then (да)
    #lightgreen:Иван выжил в молоке;
    :Здоровье = 100;
else (нет)
    #lightgreen:Иван получил урон 10;
    :Здоровье = 90;
endif

if (Третий котёл: КипяточныйБафф(100) >= 100?) then (да)
    #lightgreen:Иван выжил в кипятке;
    :Здоровье = 90;
else (нет)
    #pink:Иван погиб в кипятке;
    stop
endif

#lightgreen:Иван стал прекрасным царём!;
stop

@enduml
