@startuml
title Пошаговое взаимодействие в системе "Конёк-Горбунок"

actor "Иван" as I
participant "КонёкГорбунок" as H
participant "КотелСВодой" as WC
participant "КотелСМолоком" as MC
participant "КотелСКипятком" as BC
participant "ВодныйБафф" as WB
participant "МолочныйБафф" as MB
participant "КипяточныйБафф" as BB

' 1. Подготовка к первому котлу
I -> H : призвать()
H -> WB ** : наложитьЗащиту("вода")
note right of WB: защита = 50

' 2. Первый котёл (Вода 40°)
I -> WC : прыгнуть()
WC -> I : воздействовать(40)
note right of I: Урон 40 - 50 = 0
I -> I : выжил

' 3. Подготовка ко второму котлу
I -> H : призвать()
H -> MB ** : наложитьЗащиту("молоко")
note right of MB: защита = 50

' 4. Второй котёл (Молоко 60°)
I -> MC : прыгнуть()
MC -> I : воздействовать(60)
note right of I: Урон 60 - 50 = 10
I -> I : здоровье = 90

' 5. Подготовка к третьему котлу
I -> H : призвать()
H -> BB ** : наложитьЗащиту("кипяток")
note right of BB: защита = 100

' 6. Третий котёл (Кипяток 100°)
I -> BC : прыгнуть()
BC -> I : воздействовать(100)
note right of I: Урон 100 - 100 = 0
I -> I : выжил

' 7. Финал
note over I #lightgreen: Иван стал прекрасным царём!

@enduml
